#!/usr/bin/python

from deb_autopkg import cmd

conf   = "cf/apu2.yml"
pool   = "apu2"
target = "stretch-amd64"
kpkg   = "kernel.apu2"

cmd.pool_invalidate_target_package(conf, pool, kpkg, target)
cmd.build_pool(conf, pool)
cmd.upload_pool(conf, pool)
cmd.deploy_pool(conf, pool)
