
BUILDROOT_VG_NAME="system"
BUILDROOT_LV_NAME="sles12-buildroot"
BUILDROOT_LV_SIZE="5G"
BUILDROOT_SNAP_SIZE="10G"
BUILDROOT_TARBALL="sles12-buildroot.tar.bz2"
BUILDROOT_CHROOT_NAME="sles12-buildroot"
BUILDROOT_CHROOT_SRC="source:${BUILDROOT_CHROOT_NAME}"
