name: autobuild

on:
  push:
    branches:
      - master
      - 'release/**'
      - 'submit/**'
      - 'testing/**'
      - 'wip/**'
  pull_request:
  workflow_dispatch:

jobs:
  build-all:
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04 ]
    name: on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1440
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-worker

      # cache apt repo and state, so we don't need full rebuild every time
      # note: for different branches, need different name

      - name: Cache apt repo and state files
        id: cache-repo
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.aptrepo
            ${{ github.workspace }}/.stat
          key: repobuild-${{ matrix.os }}+${{ github.ref_name }}@${{ env.CONIFG_HASH }}
          restore-keys: |
            repobuild-${{ matrix.os }}+${{ github.ref_name }}@${{ env.CONFIG_HASH }}
            repobuild-${{ matrix.os }}+${{ github.ref_name }}@

      - uses: ./.github/actions/build-all

      # upload the generated apt repo as artifact

      - name: Archive final apt repo
        uses: actions/upload-artifact@v3
        with:
          name: aptrepo-built-on-${{ matrix.os }}-branch-${{ env.BRANCH_IDENT }}
          path: .aptrepo
